import axios from 'axios';
import { DEMO_USERS, DEMO_WELLS, DEMO_EVENTS, DEMO_RISK_ALERTS, DEMO_REPORTS, DEMO_READINGS } from './demoData';

const API_URL = import.meta.env.VITE_API_URL || '/api';

const api = axios.create({
  baseURL: API_URL,
  timeout: 5000,
});

// Attach JWT token to every request
api.interceptors.request.use((config) => {
  const token = localStorage.getItem('ertmac_token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Handle mock responses when backend server is offline or on static CDN hosting
function getMockResponse(config) {
  const url = config.url || '';
  const method = (config.method || 'get').toLowerCase();

  // Mock Login
  if (url.includes('/auth/login') && method === 'post') {
    let body = {};
    try {
      body = typeof config.data === 'string' ? JSON.parse(config.data) : config.data || {};
    } catch {}
    const email = (body.email || '').trim().toLowerCase();
    const user = DEMO_USERS[email] || DEMO_USERS['engineer@ertmac.demo'];
    return {
      status: 200,
      statusText: 'OK',
      data: {
        success: true,
        message: 'Login successful (Demo Mode).',
        token: 'demo-jwt-token-ertmac-nwis',
        user: { ...user },
      },
    };
  }

  // Mock Current User
  if (url.includes('/auth/me')) {
    const stored = localStorage.getItem('ertmac_user');
    const user = stored ? JSON.parse(stored) : DEMO_USERS['engineer@ertmac.demo'];
    return {
      status: 200,
      statusText: 'OK',
      data: { success: true, user },
    };
  }

  // Mock Wells
  if (url.includes('/wells/')) {
    const well = DEMO_WELLS[0];
    return {
      status: 200,
      statusText: 'OK',
      data: { success: true, data: { ...well, events: DEMO_EVENTS, openAlerts: 1 } },
    };
  }
  if (url.includes('/wells')) {
    return {
      status: 200,
      statusText: 'OK',
      data: { success: true, data: DEMO_WELLS, total: DEMO_WELLS.length },
    };
  }

  // Mock Events
  if (url.includes('/events')) {
    return {
      status: 200,
      statusText: 'OK',
      data: { success: true, data: DEMO_EVENTS },
    };
  }

  // Mock Risk Alerts
  if (url.includes('/risks')) {
    return {
      status: 200,
      statusText: 'OK',
      data: { success: true, data: DEMO_RISK_ALERTS },
    };
  }

  // Mock Reports
  if (url.includes('/reports')) {
    return {
      status: 200,
      statusText: 'OK',
      data: { success: true, data: DEMO_REPORTS },
    };
  }

  // Mock Readings
  if (url.includes('/readings')) {
    return {
      status: 200,
      statusText: 'OK',
      data: { success: true, data: DEMO_READINGS },
    };
  }

  // Mock Knowledge Graph
  if (url.includes('/knowledge-graph')) {
    const nodes = [
      { id: 'w-101', label: 'WELL-101', type: 'WELL', data: { field: 'Deohal Field', status: 'DRILLING' } },
      { id: 'w-103', label: 'WELL-103', type: 'WELL', data: { field: 'Deohal Field', status: 'COMPLETED' } },
      { id: 'ev-1', label: 'Mud Loss', type: 'EVENT', data: { depth: 2850, severity: 'HIGH' } },
      { id: 'fm-x', label: 'Formation-X', type: 'FORMATION' },
    ];
    const edges = [
      { source: 'w-103', target: 'ev-1', label: 'HAS_EVENT' },
      { source: 'ev-1', target: 'fm-x', label: 'IN_FORMATION' },
    ];
    return {
      status: 200,
      statusText: 'OK',
      data: { success: true, data: { nodes, edges } },
    };
  }

  // Mock AI Chat
  if (url.includes('/ai/chat')) {
    return {
      status: 200,
      statusText: 'OK',
      data: {
        success: true,
        data: {
          answer: 'Based on offset well data from WELL-103, severe mud loss (25-30 bbl/hr) was encountered at 2850m in Formation-X carbonate due to natural fractures. For active well WELL-101 (now at 2820m), recommend: 1) Maintaining mud weight at 1.32 SG, 2) Preparing 50 bbl fibrous LCM mix on standby, 3) Reducing pump rate upon reaching 2840m.',
          sources: ['WELL-103 Daily Drilling Report — Page 14 (14 March 2023)'],
          isAIGenerated: true,
          disclaimer: 'This response is generated by eRTMAC-NWIS AI decision support. Requires operational review.',
        },
      },
    };
  }

  // Generic fallback
  return {
    status: 200,
    statusText: 'OK',
    data: { success: true, data: [] },
  };
}

// Fallback interceptor
api.interceptors.response.use(
  (response) => response,
  (error) => {
    // If backend is unreachable or 404 (static deployment), return seamless mock response
    if (error.response?.status === 401 && window.location.pathname === '/login') {
      const mock = getMockResponse(error.config);
      return Promise.resolve(mock);
    }
    if (!error.response || error.response.status === 404 || error.response.status >= 500 || error.code === 'ERR_NETWORK') {
      const mock = getMockResponse(error.config);
      return Promise.resolve(mock);
    }
    return Promise.reject(error);
  }
);

export default api;
